ignore_colors = [
	[0, 0, 0, 0],
]

version = 1

[priorities]
"0" = 0

[[structure]]
name = "tud"
file = "images/tud.png"
startx = 1817
starty = 58
priority = 0

[[structure]]
name = "tud-h-line-up"
file = "images/tud-horizontal-line.png"
startx = 1817
starty = 57
priority = 0

[[structure]]
name = "tud-h-line-down"
file = "images/tud-horizontal-line.png"
startx = 1817
starty = 67
priority = 0

[[structure]]
name = "heart"
file = "images/heart.png"
startx = 1812
starty = 54
priority = 0

[[structure]]
name = "mini-lgbt-flag"
file = "images/mini-lgbt-flag.png"
startx = 1812
starty = 60
priority = 0